version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@google-cloud/storage"
    versions:
    - 5.7.3
    - 5.7.4
    - 5.8.0
    - 5.8.1
    - 5.8.2
    - 5.8.3
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: cloudinary
    versions:
    - 1.23.0
    - 1.24.0
    - 1.25.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: joi
    versions:
    - 17.3.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
